import { html, raw, render, bind } from "../ccm-ui.mjs";
const results = [];
function check(condition, name) { if (!condition) throw new Error(name); results.push(name); }
try {
  const input = '\"><img src=x onerror=alert(1)>&\'';
  const view = html`<div title="${input}">${input}</div>`;
  check(view.textContent === input && view.title === input && !view.querySelector("img"), "text and quoted attributes remain literal");
  check(html`<p>${"&lt;"}</p>`.textContent === "&lt;", "entities are not decoded twice");
  const node = html`<button>Nested</button>`;
  const list = html`<div>${[node, "<b>", 42, false, null, undefined]}</div>`;
  check(list.firstChild === node && list.textContent === "Nested<b>42", "arrays and node identity");
  check(html`<button ${true && "disabled"}>Save</button>`.disabled, "conditional attributes");
  check(!html`<button ${false && "disabled"}>Save</button>`.disabled, "absent conditional attributes");
  check(html`<span>${raw('<svg viewBox="0 0 24 24"><path /></svg>')}</span>`.firstChild.namespaceURI === "http://www.w3.org/2000/svg", "explicit SVG markup");
  check(html`<p>${{ markup: "<img>" }}</p>`.textContent === "", "ordinary objects cannot opt out of escaping");
  let clicked = 0;
  const target = document.createElement("div");
  render(html`<button data-on-click="go">A</button><button data-on-click="go">B</button>`, target, { events: { go() { clicked++; } } });
  target.querySelectorAll("button").forEach(button => button.click());
  check(clicked === 2, "fragment rendering and event binding");
  const text = html`${"Hello <world>"}`;
  render(text, target, { events: {} });
  check(target.firstChild === text && target.textContent === "Hello <world>", "text-only template renders with an instance");
  const plainText = document.createTextNode("Plain text");
  render(plainText, target, {});
  check(target.firstChild === plainText && target.textContent === "Plain text", "native text node renders with an instance");
  render(html`<button data-on-click="go">Go</button>`, target, { events: { go() { clicked++; } } });
  target.firstChild.click();
  check(clicked === 3, "single element rendering and event binding");
  const calls = [];
  const instance = { events: { go() { calls.push("go"); }, next() { calls.push("next"); } } };
  const button = html`<button data-on-click="go">Go</button>`;
  let manualCalls = 0;
  button.addEventListener("click", () => manualCalls++);
  render(button, target, instance);
  render(button, target, instance);
  button.click();
  check(calls.join() === "go", "repeated rendering does not duplicate listeners");
  calls.length = 0;
  bind(button, instance);
  bind(target, instance);
  button.click();
  check(calls.join() === "go", "rebinding a node and its ancestor does not duplicate listeners");
  calls.length = 0;
  button.setAttribute("data-on-click", "next");
  bind(button, instance);
  button.click();
  check(calls.join() === "next", "rebinding updates the action name");
  calls.length = 0;
  bind(button, { events: { next() { calls.push("replacement"); } } });
  button.click();
  check(calls.join() === "replacement", "rebinding replaces the previous instance");
  calls.length = 0;
  button.removeAttribute("data-on-click");
  bind(target, instance);
  button.click();
  check(calls.length === 0, "rebinding removes listeners for deleted attributes");
  check(manualCalls === 5, "rebinding preserves manually registered listeners");
  button.setAttribute("data-on-click", "go");
  button.setAttribute("data-on-focus", "next");
  bind(button, instance);
  bind(button, instance);
  button.click();
  button.dispatchEvent(new Event("focus"));
  check(calls.join() === "go,next", "rebinding manages multiple event types independently");
  calls.length = 0;
  const stringTarget = document.createElement("div");
  let containerCalls = 0;
  stringTarget.setAttribute("data-on-click", "container");
  const stringInstance = { events: { ...instance.events, container() { containerCalls++; } } };
  const markup = 'Text<!-- comment --><button data-on-click="go">Go</button><section><button data-on-click="next">Next</button></section>';
  render(markup, stringTarget, stringInstance);
  stringTarget.querySelectorAll("button").forEach(el => el.click());
  check(calls.join() === "go,next", "HTML strings bind top-level elements and descendants");
  stringTarget.click();
  check(containerCalls === 0, "HTML string rendering does not bind the container");
  calls.length = 0;
  render(markup, stringTarget, stringInstance);
  stringTarget.querySelectorAll("button").forEach(el => el.click());
  check(calls.join() === "go,next", "repeated HTML string rendering binds each action once");
  calls.length = 0;
  render(markup, stringTarget);
  stringTarget.querySelectorAll("button").forEach(el => el.click());
  check(calls.length === 0 && stringTarget.querySelectorAll("button").length === 2, "HTML strings render without an instance");
  document.querySelector("#result").textContent = `PASS: ${results.length} checks`;
} catch (error) {
  document.querySelector("#result").textContent = `FAIL: ${error.stack}`;
  throw error;
}
